export const FAKE_POPULARS = [{
backdrop_path :"/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
first_air_date: "2021-09-17",
genre_ids: (3)[10759, 9648, 18],
id: 93405,
name: "Squid Game",
origin_country: ['KR'],
original_language: "ko",
original_name: "오징어 게임",
overview: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
popularity: 8611.964,
poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
vote_average: 7.838,
vote_count: 14471,
},
];